services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - db
            - redis
        networks:
            - db-network
            - cache-network
            - app-network

    webserver:
        image: nginx:alpine
        ports:
            - "${APP_PORT}:80"
        volumes:
            - .:/var/www/html
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped
        networks:
            - app-network
            - db-network

    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DOCKER_DB_PORT}:3306"
        volumes:
            - ./.docker/data/db:/var/lib/mysql
        networks:
            - db-network

    redis:
        image: redis:alpine
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - "${DOCKER_REDIS_PORT}:6379"
        volumes:
            - ./.docker/data/redis:/data
        networks:
            - cache-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: ${DB_PORT}
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${PHPMYADMIN_PORT}:80"
        networks:
            - db-network

networks:
    db-network:
        driver: bridge
    cache-network:
        driver: bridge
    app-network:
        driver: bridge
